- name: install nginx
  hosts: dynamic_frontend # dynamic inventory info
  become: true # providing sudo permissions to install and start the service of nginx
  serial: 2 # configuration implement first 2 later 2 like this 
  tasks:
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: nginx service start 
    ansible.builtin.service:
      name: nginx 
      state: started