- name: nginx install
  tags: 
  - deployment
  import_role:
    name: common
    tasks_from: nginx


# - name: nginx install
#   tags: 
#     - deployment
#   include_role:
#     name: common
#     tasks_from: nginx.yaml