apiVersion: v1
kind: Deployment 
metadata:
  name: Deployment 
  labels:
    name: nginx-deployment
    project: ecom 
  annotations:
    description: "This pod runs for testing dev-stage"
    git_url: "https://github-testing.com"
    running_port: "80"
    maintainer: "royal@example.com"
spec: 
    replicas: 3
    selector: 
      matchLabels:
        name: nginx-pod # pod template
        app: frontend
    template:
      metadata:
        labels:
          selector:
            name: nginx-pod
            app: frontend
      spec:
      containers:
        - name: nginx
          image: nginx # latest will be taken by default
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
              - containerPort: 80
          env: 
            - name: ENVIRONMENT
              value: "dev" 
          envFrom:
            - secretRef:
                name: mySecrets  
            - configMapRef:
              name: myconfigmap