apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    name: nginx-pod
    app: frontend
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #service-por