apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment 
  labels:
    name: nginx
    project: ecom 
spec: 
  replicas: 8
  selector: 
    matchLabels:
      name: nginx # pod template
      tier: frontend
  template:
    metadata:
      labels:
        name: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:perl # latest will be taken by default
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
              - containerPort: 80   
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    name: nginx
    tier: frontend
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #service-por