- name: play-1 
  hosts: local
  connection: local # no require to username and password
  tasks: 
  - name: hello with task-1 from play-1 
    ansible.builtin.debug: 
      msg: "Hello with task-1 from play-1"
  - name: hello with task-2 from play-1 
    ansible.builtin.debug:
      msg: "Hello with task-2 from play-1"


- name: play-2
  hosts: local
  connection: local
  tasks:
  - name: hello with task-1 from play-2 
    ansible.builtin.debug:
      msg: "Hello with task-1 from play-2"
  - name: hello with task-2 from play-2 
    ansible.builtin.debug:
      msg: "Hello with task-2 from play-2"


- name: Create a directory
  hosts: allapp
  become: true
  tasks:
  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /opt/backup-t4q3
      state: directory
