- name: shell practice
  hosts: local
  connection: local
  tasks:  
  - name: shell module  # like exit status in shell 
    ansible.builtin.shell: "ls -lrta > result.txt" # like exit status in shell
    register: shell_result  

  - name: print output from shell 
    ansible.builtin.debug: 
      msg: "{{ shell_result }}"

  - name: command module 
    ansible.builtin.command: "ls -lrta "
    register: command_result 

  - name: print output from command 
    ansible.builtin.debug: 
      msg: "{{ command_result }}"
  
  