- name: uninstall nginx
  hosts: dynamic_frontend # dynamic inventory info
  become: true # providing sudo permissions to install and start the service of nginx
  tasks:
  - name: nginx service start 
    ansible.builtin.service:
      name: nginx 
      state: stopped

  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: absent
  
