apiVersion: v1
kind: Pod 
metadata:
  name: nginx 
  labels:
    component: frontend
    environment: dev
spec:
  containers:
    - name: nginx 
      image: nginx # latest will be taken by default
      env: 
        - name: CATALOGUE_HOST
          value: "catalogue.royalreddy.site"
        - name: USER_HOST
          value: "user.royalreddy.site"