apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: nginx
  labels:
    name: nginx
    project: ecom
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: nginx # pod template
      tier: frontend
  template:
    metadata:
      labels:
        name: nginx
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx # latest will be taken by default
