- name: install nginx
  hosts: frontend
  become: true
  tasks:
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: nginx service start 
    ansible.builtin.service:
      name: nginx 
      state: started