- name: variables practice
  hosts: local
  connection: local
  var:
    NAME: Royal Reddy 
    ROLE: DevOps Engineer
    LOCATION: HYDERABAD
  tasks:
  - name: about a employee
    ansible.builtin.debug:
      msg: 'I am {{ NAME }} , From {{ LOCATION }}, Working as {{ ROLE }}'