- name: practice variables 
  hosts: local
  connection: local
  vars_files:
    info.yaml
  tasks:
  - name: variables from file 
    ansible.builtin.debug:
      msg: 'I am {{ NAME }} , From {{ LOCATION }}, Working as {{ ROLE }}'