- name: task and play level variables
  hosts: local
  connection: local
  vars_files:
    info.yaml
  vars_prompt:
    - name: NAME
      prompt: Enter name?
      private: false
  vars:
    NAME: from-play-level
  tasks: 
  - name: about employee
    vars: 
      NAME: from-task-level
    ansible.builtin.debug:
      msg: 'I am {{ NAME }}'