- name: variables practice
  hosts: local
  connection: local
  vars:
    NAME: Royal Reddy 
    ID: 12
    CERTIFIED: false 
    SKILLS:
      - Linux
      - Shell script
      - Ansible
    TOOLS: 
      CLOUD: AWS
      IaC: Terraform
  tasks:
  - name: about a employee
    ansible.builtin.debug:
      msg: 'I am {{ NAME }} , ID {{ ID }}, am I Certified  {{ CERTIFIED }} skills {{ SKILLS[2] }} , IaC-Tool-{{ TOOLS[IaC] }}'