- name: functions providing default variables
  hosts: local
  connection: local
  tasks:
  - name: about a employee
    ansible.builtin.debug:
      msg: "I am {{ NAME | default('Royal') }}"
    
  - name: string to list
    vars: 
      persons: "Ramesh,Hitesh,Naresh,Mahesh"
    ansible.builtin.debug:
      msg: "{{ persons | split(',') }}"

  - name: dictionary into a list 
    vars:
      TOOLS: 
        CLOUD: AWS
        IaC: Terraform
        CICD: Jenkins
    ansible.builtin.debug:
      msg: "{{ TOOLS | dict2items  }}"