- name: functions providing default variables
  hosts: local
  connection: local
  tasks:
  - name: about a employee
    ansible.builtin.debug:
      msg: "I am {{ NAME | default('Royal') }}"
    
  - name: string to list
    vars: 
      persons: "Ramesh,Hitesh,Naresh,Mahesh"
      ansible.builtin.debug:
        msg: "{{ persons | split(',') }}"