apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: nginx-service
    app: frontend
spec:
  selector:
    name: nginx-service
    app: frontend
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-service
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "300m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
