- name: local configuration
  hosts: local
  connection: local
  become: true 
  tasks:
  - name: install python botocore and boto3
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - botocore
    - boto3