FROM almalinux:latest

# create directory for application 
RUN mkdir ecommerce_application

# check present directory
RUN pwd 

# move to ecommerce_application repo 
WORKDIR /ecommerce_application

# check present directory
RUN pwd

# maintain container in active time of check 
CMD ["sleep" "1000"]