apiVersion: v1
kind: Pod 
metadata:
  name: nginx 
  labels:
    environment: dev
    app: web-server
    tier: frontend
    project: ecom
spec:
  containers:
    - name: nginx 
      image: nginx # latest will be taken by default