apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ecom-app
  region: us-east-1
managedNodeGroups:
  - name: ecom-app-node
    instanceTypes: ["t3.large","c3.large","c4.large","c5.large"]
    minSize: 2
    desiredCapacity: 2
    maxSize: 3
    spot: true # dot not preferable for production 