apiVersion: v1
kind: Pod 
metadata:
  name: nginx 
  labels:
    environment: dev
    app: web-server
    tier: frontend
    project: ecom
  annotations:
    description: "This pod runs for testing dev-stage"
    git_url: "https://github-testing.com"
    running_port: "80"
    maintainer: "royal@example.com"
spec:
  containers:
    - name: nginx 
      image: nginx # latest will be taken by default